services:
  backend:
    container_name: Backend-Coney
    dns:
      - 8.8.8.8
      - 1.1.1.1
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - NODE_ENV=development
      - APP_PORT=${APP_PORT}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - .:/var/www/app
      - /var/www/app/node_modules

